language: minimal
branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always

stages:
  - name: 'NetStandard-2.1.502'
  - name: 'NetStandard-2.2.101'
  - name: 'NetStandard-2.2.205'
  - name: 'NetStandard-2.2.301'
  - name: 'NetStandard-2.2.401'

jobs:
  include:
    - stage: 'NetStandard-2.1.502'
      language: csharp
      solution: VWOSdk.sln
      sudo: required
      dist: trusty
      dotnet: 2.1.502
      mono: none
      os:
        - linux
      install:
      - dotnet restore
      script:
        - dotnet build
        - cd minicover && dotnet restore
        - dotnet minicover instrument --workdir ../ --assemblies "VWOSdk.Tests/**/bin/**/*.dll" --sources  "VWOSdk/**/*.cs" --exclude-sources "VWOSdk.Tests/**/*.cs"
        - dotnet minicover reset --workdir ../
        - cd ..
        - dotnet test --no-build ./VWOSdk.Tests/VWOSdk.Tests.csproj
        - cd minicover
        - dotnet minicover report --workdir ../ --threshold 95
        - dotnet minicover coverallsreport --help
        - dotnet minicover coverallsreport --root-path ../ --workdir ../ --service-name "travis-ci" --service-job-id "$TRAVIS_JOB_ID"

    - stage: 'NetStandard-2.2.101'
      language: csharp
      solution: VWOSdk.sln
      sudo: required
      dist: xenial
      dotnet: 2.2.101
      mono: none
      os:
        - linux
      install:
      - dotnet restore
      script:
        - dotnet build
        - cd minicover && dotnet restore
        - dotnet minicover instrument --workdir ../ --assemblies "VWOSdk.Tests/**/bin/**/*.dll" --sources  "VWOSdk/**/*.cs" --exclude-sources "VWOSdk.Tests/**/*.cs"
        - dotnet minicover reset --workdir ../
        - cd ..
        - dotnet test --no-build ./VWOSdk.Tests/VWOSdk.Tests.csproj
        - cd minicover
        - dotnet minicover report --workdir ../ --threshold 95
        - dotnet minicover coverallsreport --help
        - dotnet minicover coverallsreport --root-path ../ --workdir ../ --service-name "travis-ci" --service-job-id "$TRAVIS_JOB_ID"

    - stage: 'NetStandard-2.2.205'
      language: csharp
      solution: VWOSdk.sln
      sudo: required
      dist: xenial
      dotnet: 2.2.205
      mono: none
      os:
        - linux
      install:
      - dotnet restore
      script:
        - dotnet build
        - cd minicover && dotnet restore
        - dotnet minicover instrument --workdir ../ --assemblies "VWOSdk.Tests/**/bin/**/*.dll" --sources  "VWOSdk/**/*.cs" --exclude-sources "VWOSdk.Tests/**/*.cs"
        - dotnet minicover reset --workdir ../
        - cd ..
        - dotnet test --no-build ./VWOSdk.Tests/VWOSdk.Tests.csproj
        - cd minicover
        - dotnet minicover report --workdir ../ --threshold 95
        - dotnet minicover coverallsreport --help
        - dotnet minicover coverallsreport --root-path ../ --workdir ../ --service-name "travis-ci" --service-job-id "$TRAVIS_JOB_ID"

    - stage: 'NetStandard-2.2.301'
      language: csharp
      solution: VWOSdk.sln
      sudo: required
      dist: xenial
      dotnet: 2.2.301
      mono: none
      os:
        - linux
      install:
      - dotnet restore
      script:
        - dotnet build
        - cd minicover && dotnet restore
        - dotnet minicover instrument --workdir ../ --assemblies "VWOSdk.Tests/**/bin/**/*.dll" --sources  "VWOSdk/**/*.cs" --exclude-sources "VWOSdk.Tests/**/*.cs"
        - dotnet minicover reset --workdir ../
        - cd ..
        - dotnet test --no-build ./VWOSdk.Tests/VWOSdk.Tests.csproj
        - cd minicover
        - dotnet minicover report --workdir ../ --threshold 95
        - dotnet minicover coverallsreport --help
        - dotnet minicover coverallsreport --root-path ../ --workdir ../ --service-name "travis-ci" --service-job-id "$TRAVIS_JOB_ID"

    - stage: 'NetStandard-2.2.401'
      language: csharp
      solution: VWOSdk.sln
      sudo: required
      dist: xenial
      dotnet: 2.2.401
      mono: none
      os:
        - linux
      install:
      - dotnet restore
      - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
      script:
      - dotnet build
      - cd minicover && dotnet restore
      - dotnet minicover instrument --workdir ../ --assemblies "VWOSdk.Tests/**/bin/**/*.dll" --sources  "VWOSdk/**/*.cs" --exclude-sources "VWOSdk.Tests/**/*.cs"
      - dotnet minicover reset --workdir ../
      - cd ..
      - dotnet test --no-build ./VWOSdk.Tests/VWOSdk.Tests.csproj
      - cd minicover
      - dotnet minicover report --workdir ../ --threshold 95
      - dotnet minicover coverallsreport --help
      - dotnet minicover coverallsreport --root-path ../ --workdir ../ --service-name "travis-ci" --service-job-id "$TRAVIS_JOB_ID"
